[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "\t" }
[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "\t" }
[[language]]
name = "css"
indent = { tab-width = 4, unit = "\t" }
[[language]]
name = "scss"
indent = { tab-width = 4, unit = "\t" }
[[language]]
name = "html"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "rust"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }
[[language]]
name = "toml"
indent = { tab-width = 4, unit = "\t" }
